# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a63a2bd6edb77f9741c663da98f55e0cf4daa8b4078af76b4986ce60e3d453b97f51257be2878e354772c8b5c5719216876f8e33f5c0cd81b780d669e10aa9

test:
  secret_key_base: 17e6a4aaefff25015bcd4910d090df20c2b447060e91fab5c8ef73cc74d1684c1531dee5194453a507705832b3ad74833391334684c1361582f48e3de62e94e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
